DROP TABLE IF EXISTS themes;
CREATE TABLE themes (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    content VARCHAR(MAX) NOT NULL,
    created_at DATETIME NOT NULL
);

DROP TABLE IF EXISTS posts_themes;
CREATE TABLE posts_themes (
    post_id INTEGER NOT NULL,
    themes_id INTEGER NOT NULL,
    PRIMARY KEY (post_id, themes_id)
);